### ISSUE TITLE
dataloader

### ISSUE THREAD

**Issue by Yysheepsheep** [jmiemirza/DILAM#2]
Hello, I encountered this issue during the process of reproducing the code and I don't know how to modify it. Could you please guide me

**Comment by Yysheepsheep** [comment]
![Uploading image.png…]()

**Comment by Yysheepsheep** [comment]
[TRAINING] Run 0 - Task fog
[TRAINING] ###########Param to Optimize###########: 140
[TRAINING] ADAPTATING BATCH NORMS...
[MAIN] Exception occured:
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    main(args)
  File "main.py", line 51, in main
    dilam(net, args, verbose=args.verbose)
  File "/root/autodl-tmp/DILAM-master/DILAM-master/dilam.py", line 43, in dilam
    dilam_adapt(model=net, opt=opt, adapt_all_bn_layers=opt.dilam_adapt_all, augment=augment)
  File "/root/autodl-tmp/DILAM-master/DILAM-master/dilam.py", line 268, in dilam_adapt
    ap = test(batch_size=tmp_batch_size,
  File "/root/miniconda3/envs/yyy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/DILAM-master/DILAM-master/utils/testing_yolov3.py", line 45, in test
    assert model and dataloader, 'Model and Loader need to be passed to yolov3 test'
AssertionError: Model and Loader need to be passed to yolov3 test
